linters:
  disable-all: true
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - ireturn
    - misspell
    - nakedret
    - nilnil
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
